= CloudBees action: Configure Git global credentials

Use this action to set up a Git global configuration for use in CloudBees workflows. 
This action authenticates the current user, by default scoped to repositories in the same organization as the workflow repository. 
After this step is run, all steps using the Git CLI in the same job authenticate with these credentials.

== Disclaimer
This repository is provided "as-is", and serves as a reference only. 
Treat this action as an example only, and test before deploying to production.
CloudBees does not warrant that any contents of this repository are free from 
defects or designed to meet any user's business requirements. 
CloudBees does not make any other warranties, express or implied, statutory or 
otherwise, including but not limited to implied warranties of merchantability, 
title, fitness for a particular purpose, or noninfringement. 

== License
This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== Reference
For more information on using actions in developing CloudBees workflows, refer
 to the link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[CloudBees platform documentation].
