= CloudBees action: Configure Git global credentials

Use this action to set up a Git global configuration for use in CloudBees workflows.
This action authenticates the current user, by default scoped to repositories in the same organization as the workflow repository.
After this step is run, all steps using the Git CLI in the same job authenticate with these credentials.

TIP: You can use this action to avoid failures due to lack of pre-authentication of private repositories. For example, if you are building a Go module that depends on other private modules, private repository authentication must be already in place for `go mod download` to run successfully.

[NOTE]
====
This action may set up authentication for different types of Git global configurations, including:

* link:https://git-scm.com/docs/gitcredentials#_custom_helpers[Git credentials helpers].
* link:https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf[`+url.<base>.insteadOf+` rules].
* link:https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresshCommand[`core.sshCommand` rule] to override the default user link:https://man7.org/linux/man-pages/man5/ssh_config.5.html[`+~/.ssh/config+`] configuration file, and specify per-host SSH private keys.

CloudBees recommends that if you are using a Git client other than the official Git CLI, make sure that your Git client supports the authentication configuration applied by this action.
====

== Inputs

[cols="2a,1a,3a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `repositories`
| String
| Yes
| Repository clone URL. https://github.com/user/repo
For listing multiple repositories, CloudBees recommends using a line break separator, although the `repositories` parameter is a whitespace and/or comma-separated list.

| `ssh-key`
| String
| No
| SSH key used to fetch the repository.
The SSH key used for fetching a repository using it's SSH clone URL (passed via the `repositories` input). The SSH key input is only relevant when the user defines an SSH clone URL via the `repositories` input. In all other cases the action fetches the pre-configured credentials setup on Unify for the specified `repositories`.

We recommend using the platform authentication instead of SSH keys.   Do not use SSH keys if using the  authentication built into the platform for the workflow repository or  authentication using the `configure-git-global-credentials` action is possible.



| `ssh-known-hosts`
| String
| No
| A list of known SSH hosts that should be added to the global host database. Use the utility `ssh-keyscan` to get public SSH keys for a host.

The public keys for GitHub and Bitbucket are added by default.

| `ssh-strict`
| Boolean
| No
| Default is `true`. When `true`, performs strict host key checking, by adding the options `StrictHostKeyChecking=yes` and `CheckHostIP=no` to the SSH command line.
Use the input `ssh-known-hosts` to configure additional hosts.

|===

== Usage examples

=== For multiple repositories, onboard the specific repositories by creating integration

In your YAML file, add:

[source,yaml]
----
      - name: Git global credentials
        uses: cloudbees-io/configure-git-global-credentials@v2
        with:
          repositories: |
            https://github.com/user1/repo
            https://github.com/user2/rep1
----

For configuring access for all repositories within a GitHub project/user namespace, you can specify the Project URL as an input: https://github.com/org/

[source,yaml]
----
      - name: Git global credentials
        uses: cloudbees-io/configure-git-global-credentials@v2
        with:
          repositories: https://github.com/org/
----

If they belong to the same scm provider, use the url https://github.beescloud.com/

[source,yaml]
----
      - name: Git global credentials
        uses: cloudbees-io/configure-git-global-credentials@v2
        with:
          repositories: https://github.beescloud.com/
----

=== Using SSH, add the SSH key as a Secret property on Unify and use the SSH clone url in the `repositories` input.

NOTE: When defining the SSH key secret please ensure that there is a new line at the end of the secret.

In your YAML file, add:

[source,yaml]
----
      - name: Git global credentials
        uses: cloudbees-io/configure-git-global-credentials@v2
        with:
          repositories: "ssh://github.com/user/repo"
          ssh-key: ${{secrets.<ssh-secret-name-placeholder>}}
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].
