apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'Configure Git Global Credentials'
description: 'Configures credentials in the Git global configuration'
inputs:
  repositories:
    description: >
      Repository clone URL. separated by commas or spaces or newlines
      For example, "https://github.com/user/repo" or "https://github.com/user/repo1, https://github.com/user/repo2" or "https://github.com/user/repo1 https://github.com/user/repo2"
      when using with ssh-key input, provide based urls like "ssh://github.com/user/repo"
    required: false
    default: "${{ cloudbees.scm.repositoryUrl }}"
  cloudbees-api-token:
    description: >
      The CloudBees API Token to use for fetching SCM tokens unless `token` or `ssh-key` have been configured
    default: "${{ cloudbees.api.token }}"
  cloudbees-api-url:
    description: The CloudBees API root URL to use for fetching SCM tokens
    default: "${{ cloudbees.api.url }}"
  ssh-key:
    description: >
      SSH key used to fetch repositories. The SSH key is configured with the global
      git config, which enables your scripts to run authenticated git commands.

      NOTE: the SSH key will only be used by Git clients that understand how to use
      the `core.sshCommand` configuration key. If you are using a custom Git client that
      cannot process a custom `core.sshCommand` then the SSH key configuration will be
      ignored by that client. The standard Git CLI will process the `core.sshCommand`
      configuration.

      NOTE: the SSH key will be configured for all SSH remotes. This option is not
      compatible with specifying `repositories` as the SSH key has to be installed
      for all SSH repositories.

      We recommend using a service account with the least permissions necessary.
  ssh-known-hosts:
    description: >
      Known hosts in addition to the user and global host key database. The public
      SSH keys for a host may be obtained using the utility `ssh-keyscan`. For example,
      `ssh-keyscan github.com`. The public keys for github.com, bitbucket.org and gitlab.com are always implicitly added.
  ssh-strict:
    description: >
      Whether to perform strict host key checking. When true, adds the options `StrictHostKeyChecking=yes`
      and `CheckHostIP=no` to the SSH command line. Use the input `ssh-known-hosts` to
      configure additional hosts.
    default: "true"
runs:
  using: composite
  steps:
    - name: Configure Git Global Credentials
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/configure-git-global-credentials:${{ action.scm.sha }}
      env:
        CLOUDBEES_EVENT_PATH: /cloudbees/event.json
        INPUT_REPOSITORIES: "${{ inputs.repositories }}"
        INPUT_SSH_KEY: "${{ inputs.ssh-key }}"
        INPUT_SSH_KNOWN_HOSTS: "${{ inputs.ssh-known-hosts }}"
        INPUT_SSH_STRICT: "${{ inputs.ssh-strict }}"
        INPUT_CLOUDBEES_API_TOKEN: "${{ inputs.cloudbees-api-token }}"
        INPUT_CLOUDBEES_API_URL: "${{ inputs.cloudbees-api-url }}"
      with:
        args: "configure"
        entrypoint: "configure-git-global-credentials"
