apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'Configure Git Global Credentials'
description: 'Configures credentials in the Git global configuration'
inputs:
  repositories:
    description: >
      Whitespace and/or comma separated list of repository names with owner. For example, `actions/checkout`.
      Alternatively if provider is `custom` then this is the clone URL of the repositories

      If not specified and the `provider` has not been overridden the action will try to infer what the value should be
      from the triggering event. For example if this action is run in the GitHub repository `example/foo` then the
      inferred default repositories value would be `example/*`

      If a default value cannot be inferred then the action will fail in anticipation that you will explicitly
      configure the value for subsequent runs.

      Configuring this value in conjunction with `ssh-key` is an error as the SSH key has to be installed for all SSH
      repositories.
    required: false
    default: "${{ cloudbees.scm.repositoryUrl }}"
  cloudbees-api-token:
    description: >
      The CloudBees API Token to use for fetching SCM tokens unless `token` or `ssh-key` have been configured
    default: "${{ cloudbees.api.token }}"
  cloudbees-api-url:
    description: The CloudBees API root URL to use for fetching SCM tokens
    default: "${{ cloudbees.api.url }}"
  ssh-key:
    description: >
      SSH key used to fetch repositories. The SSH key is configured with the global
      git config, which enables your scripts to run authenticated git commands.

      NOTE: the SSH key will only be used by Git clients that understand how to use
      the `core.sshCommand` configuration key. If you are using a custom Git client that
      cannot process a custom `core.sshCommand` then the SSH key configuration will be
      ignored by that client. The standard Git CLI will process the `core.sshCommand`
      configuration.

      NOTE: the SSH key will be configured for all SSH remotes. This option is not
      compatible with specifying `repositories` as the SSH key has to be installed
      for all SSH repositories.

      We recommend using a service account with the least permissions necessary.
  ssh-known-hosts:
    description: >
      Known hosts in addition to the user and global host key database. The public
      SSH keys for a host may be obtained using the utility `ssh-keyscan`. For example,
      `ssh-keyscan github.com`. The public keys for github.com, bitbucket.org and gitlab.com are always implicitly added.
  ssh-strict:
    description: >
      Whether to perform strict host key checking. When true, adds the options `StrictHostKeyChecking=yes`
      and `CheckHostIP=no` to the SSH command line. Use the input `ssh-known-hosts` to
      configure additional hosts.
    default: "true"
runs:
  using: composite
  steps:
    - name: Configure Git Global Credentials
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/configure-git-global-credentials:${{ action.scm.sha }}
      env:
        CLOUDBEES_EVENT_PATH: /cloudbees/event.json
        INPUT_REPOSITORIES: "${{ inputs.repositories }}"
        INPUT_TOKEN: "${{ inputs.token }}"
        INPUT_SSH_KEY: "${{ inputs.ssh-key }}"
        INPUT_SSH_KNOWN_HOSTS: "${{ inputs.ssh-known-hosts }}"
        INPUT_SSH_STRICT: "${{ inputs.ssh-strict }}"
        INPUT_CLOUDBEES_API_TOKEN: "${{ inputs.cloudbees-api-token }}"
        INPUT_CLOUDBEES_API_URL: "${{ inputs.cloudbees-api-url }}"
      with:
        args: "configure"
        entrypoint: "configure-git-global-credentials"
