apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: SelfTest

on:
  push:
    branches:
      - "*"

jobs:
  build:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - name: Setup git credentials
        uses: cloudbees-io/configure-git-global-credentials@v1
      - id: build-and-test
        name: Build and test
        uses: docker://golang:1.21
        run: |
          go test ./...
      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v0
        with:
          registry: ${{ vars.STAGING_DOCKER_REGISTRY }}
          username: ${{ secrets.STAGING_DOCKER_USERNAME }}
          password: ${{ secrets.STAGING_DOCKER_PASSWORD }}
      - id: build-image
        name: Build image
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          destination: ${{ vars.STAGING_DOCKER_REGISTRY }}/staging/configure-git-global-credentials:${{ cloudbees.scm.sha }}${{ cloudbees.scm.branch == 'main' && format(',{0}/staging/configure-git-global-credentials:1.0.11', '{0}/staging/configure-git-global-credentials:latest', vars.STAGING_DOCKER_REGISTRY),  || format('{0}/staging/configure-git-global-credentials:{1}', vars.STAGING_DOCKER_REGISTRY, cloudbees.version) }}
          context: ${{ cloudbees.workspace }}

  check-pat:
    steps:
      - uses: .
        with:
          token: ${{ secrets.IO_CONFIG_GIT_GLOBAL_PAT }}
      - uses: docker://alpine/git:2.40.1
        run: |
          git clone https://github.com/cloudbees-io/checkout.git
  check-ssh:
    steps:
      - id: decode-sshkey
        uses: docker://alpine:3.18
        run: |
          echo "$SSHKEY" | base64 -d | printf %s > $CLOUDBEES_OUTPUTS/sshkey
        env:
          SSHKEY: ${{ secrets.IO_CONFIG_CHECKOUT_RO_DEPLOY_KEY }}
      - uses: .
        with:
          ssh-key: ${{ steps.decode-sshkey.outputs.sshkey }}
      - uses: docker://alpine/git:2.40.1
        run: |
          git clone https://github.com/cloudbees-io/checkout.git
  check-fancy:
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: cloudbees-io/configure-git-global-credentials@v1
      - uses: docker://alpine/git:2.40.1
        run: |
          git clone https://github.com/cloudbees-io/checkout.git
  check-fancy2:
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: cloudbees-io/configure-git-global-credentials@v1
        with:
          repositories: calculi-corp/*
      - uses: docker://alpine/git:2.40.1
        run: |
          git clone https://github.com/calculi-corp/ng-dsl-example.git
  check-fancy3:
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: cloudbees-io/configure-git-global-credentials@v1
        with:
          repositories: calculi-corp/*
      - uses: docker://alpine/git:2.40.1
        run: |
          git clone https://github.com/calculi-corp/scm-service.git
  check-fancy4:
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: cloudbees-io/configure-git-global-credentials@v1
        with:
          repositories: calculi-corp/*
      - uses: docker://golang:1.21
        run: |
          mkdir test
          cd test
          go mod init example.com/test
          export GOPRIVATE=github.com/calculi-corp
          go get github.com/calculi-corp/jwt-validator
