apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: SelfTest

on:
  push:
    branches:
      - "*"

jobs:
  check-pat:
    steps:
      - uses: .
        with:
          token: ${{ secrets.IO_CONFIG_GIT_GLOBAL_PAT }}
      - uses: docker://alpine/git:2.40.1
        run:
          git clone https://github.com/cloudbees-io/checkout.git
  check-ssh:
    steps:
      - id: base64-decoded
        uses: docker://alpine:3.17
        run: |
          echo "${{ secrets.IO_CONFIG_CHECKOUT_RO_DEPLOY_KEY }}" | base64 -d > $CLOUDBEES_OUTPUTS/ssh-key
      - uses: .
        with:
          ssh-key: ${{ steps.base64-decoded.outputs.ssh-key }}
      - uses: docker://alpine/git:2.40.1
        run:
          git clone https://github.com/cloudbees-io/checkout.git
  check-fancy:
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: cloudbees-io/configure-git-global-credentials@v1.0.4
      - uses: docker://alpine/git:2.40.1
        run:
          git clone https://github.com/cloudbees-io/checkout.git
  check-fancy2:
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: cloudbees-io/configure-git-global-credentials@v1.0.4
        with:
          repositories: calculi-corp/*
      - uses: docker://alpine/git:2.40.1
        run:
          git clone https://github.com/calculi-corp/ng-dsl-example.git
  check-fancy3:
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: cloudbees-io/configure-git-global-credentials@v1.0.4
        with:
          repositories: calculi-corp/*
      - uses: docker://alpine/git:2.40.1
        run:
          git clone https://github.com/calculi-corp/scm-service.git
