apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: SelfTest

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  build:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com' || cloudbees.api.url == 'https://api.cloudbees.io'
    permissions:
      scm-token-own: read
      scm-token-org: read
      id-token: write
    steps:
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Self Test
        uses: docker://golang:1.26.0
        run: |
          make verify

      - id: build-image
        name: Build, scan and push to ECR
        uses: calculi-corp/cb-internal-shared-actions/build/action@v8
        with:
          go-binary-build: "true"
          go-binary-name: configure-git-global-credentials
          kaniko-build: "true"
          run-unit-test: "false"
          registry-url: 020229604682.dkr.ecr.us-east-1.amazonaws.com
          registry-image-name: actions/configure-git-global-credentials
          registry-type: ECR
          oidc-iam-role: ${{ vars.oidc_staging_iam_role }}

  test-ssh-key:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    steps:
      - id: decode-sshkey
        uses: docker://alpine:3.20
        run: |
          echo "$SSHKEY" | base64 -d | printf %s > $CLOUDBEES_OUTPUTS/sshkey
        env:
          SSHKEY: ${{ secrets.IO_CONFIG_CHECKOUT_RO_DEPLOY_KEY }}

      - uses: ./.cloudbees/testing
        with:
          ssh-key: ${{ steps.decode-sshkey.outputs.sshkey }}

      - uses: docker://alpine/git:2.45.2
        run: |
          git clone https://github.com/cloudbees-io/checkout.git

  test-job-token-own-gh-org:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: ./.cloudbees/testing
        with:
          repositories: https://github.com/calculi-corp/core-data-cache

      - uses: docker://alpine/git:2.45.2
        run: |
          # using private repo with a integration
          git clone https://github.com/calculi-corp/core-data-cache

  test-job-token-own-cb-org:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: ./.cloudbees/testing
        with:
          # a repository in the same CloudBees org as this repo even if differing GitHub org
          repositories: https://github.com/calculi-corp

      - uses: docker://alpine/git:2.45.2
        run: |
          git clone https://github.com/calculi-corp/scm-service.git

  test-job-token-go-get:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: ./.cloudbees/testing
      - uses: docker://golang:1.26.0
        run: |
          mkdir test
          cd test
          go mod init example.com/test
          export GOPRIVATE=github.com/calculi-corp
          go get github.com/calculi-corp/jwt-validator
