apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: SelfTest

on:
  push:
    branches:
      - "*"

jobs:
  build:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com' || cloudbees.api.url == 'https://api.cloudbees.io'
    permissions:
      scm-token-own: read
      id-token: write
    steps:
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Self Test
        uses: docker://golang:1.23.4
        run: |
          make verify

      - name: Login to AWS
        uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.oidc_staging_iam_role }}
          role-duration-seconds: "3600"

      - name: Configure container registry for Staging ECR
        uses: https://github.com/cloudbees-io/configure-ecr-credentials@v1

      - name: Build image
        uses: https://github.com/cloudbees-io/kaniko@v1
        with:
          destination: 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/configure-git-global-credentials:${{ cloudbees.scm.sha }},020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/configure-git-global-credentials:latest
          labels: maintainer=sdp-pod-3,email=engineering@cloudbees.io

  test-pat:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    steps:
      - uses: ./.cloudbees/testing
        with:
          token: ${{ secrets.IO_CONFIG_GIT_GLOBAL_PAT }}

      - uses: docker://alpine/git:2.45.2
        run: |
          git clone https://github.com/cloudbees-io/checkout.git

  test-ssh-key:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    steps:
      - id: decode-sshkey
        uses: docker://alpine:3.20
        run: |
          echo "$SSHKEY" | base64 -d | printf %s > $CLOUDBEES_OUTPUTS/sshkey
        env:
          SSHKEY: ${{ secrets.IO_CONFIG_CHECKOUT_RO_DEPLOY_KEY }}

      - uses: ./.cloudbees/testing
        with:
          ssh-key: ${{ steps.decode-sshkey.outputs.sshkey }}

      - uses: docker://alpine/git:2.45.2
        run: |
          git clone https://github.com/cloudbees-io/checkout.git

  test-job-token-own-gh-org:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: ./.cloudbees/testing

      - uses: docker://alpine/git:2.45.2
        run: |
          git clone https://github.com/cloudbees-io/checkout.git

  test-job-token-own-cb-org:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: ./.cloudbees/testing
        with:
          # a repository in the same CloudBees org as this repo even if differing GitHub org
          repositories: calculi-corp/*

      - uses: docker://alpine/git:2.45.2
        run: |
          git clone https://github.com/calculi-corp/scm-service.git

  test-job-token-go-get:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    permissions:
      scm-token-own: read
      scm-token-org: read
    steps:
      - uses: ./.cloudbees/testing
        with:
          repositories: calculi-corp/*
      - uses: docker://golang:1.23.4
        run: |
          mkdir test
          cd test
          go mod init example.com/test
          export GOPRIVATE=github.com/calculi-corp
          go get github.com/calculi-corp/jwt-validator
